image:
  name: docker:latest
  entrypoint: [""]

services:
  - docker:dind

stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  IMAGE: ${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}

build:
  stage: build
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker compose -f docker-compose-ci.yml pull
    - docker compose -f docker-compose-ci.yml build
    - docker compose -f docker-compose-ci.yml push
  only:
    - main

deploy:
  stage: deploy
  before_script:
    - apk add --update openssh-client
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p -m 0600 /root/.ssh
    - ssh-keyscan $SSH_SERVER >> /root/.ssh/known_hosts
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - chmod +x ./setup_env.sh
    - sh ./setup_env.sh
  script:
    - docker -H ssh://$SSH_USER@$SSH_SERVER -f docker-compose.yml compose pull
    - docker -H ssh://$SSH_USER@$SSH_SERVER -f docker-compose.yml compose up -d
    - docker -H ssh://$SSH_USER@$SSH_SERVER image prune
  only:
    - main
  when:
    - manual
