version: "3.8"

services:
  django: &django
    build:
      context: ./src
      dockerfile: multistage.Dockerfile
    command: /usr/src/start.sh
    volumes:
      - ./src/:/usr/src/
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=foo
      - SQL_ENGINE=django.db.backends.postgresql
      - SQL_DATABASE=devel
      - SQL_USER=user
      - SQL_PASSWORD=password
      - SQL_HOST=db
      - SQL_PORT=5432
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:12.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=devel

  redis:
    image: redis:latest
    volumes:
      - redis_data:/var/lib/redis/data

  celery-worker:
    <<: *django
    command: celery -A app.celery.app worker -l INFO
    ports: [ ]
    depends_on:
      - django
      - redis

volumes:
  postgres_data:
  redis_data:
