version: "3.8"

services:
  django:
    build:
      context: ./src
      dockerfile: multistage.Dockerfile
      cache_from:
        - ${IMAGE}:latest
    image: ${IMAGE}:${CI_COMMIT_SHORT_SHA}

  prometheus:
    build:
      context: ./prometheus
      dockerfile: Dockerfile
      cache_from:
        - ${IMAGE}:prometheus
    image: ${IMAGE}:prometheus
