apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitlab-external-secret
spec:
  refreshInterval: 1h

  secretStoreRef:
    kind: SecretStore
    name: gitlab-secret-store # Must match SecretStore on the cluster

  target:
    name: gitlab-external-secret # Name for the secret to be created on the cluster
    creationPolicy: Owner

  data:
    - secretKey: DEBUG # Key given to the secret to be created on the cluster
      remoteRef:
        key: DEBUG # Key of the variable on Gitlab
    - secretKey: SECRET_KEY
      remoteRef:
        key: SECRET_KEY
    - secretKey: SQL_HOST
      remoteRef:
        key: SQL_HOST
    - secretKey: SQL_PORT
      remoteRef:
        key: SQL_PORT
    - secretKey: SQL_DATABASE
      remoteRef:
        key: SQL_DATABASE
    - secretKey: SQL_USER
      remoteRef:
        key: SQL_USER
    - secretKey: SQL_PASSWORD
      remoteRef:
        key: SQL_PASSWORD
    - secretKey: SQL_ENGINE
      remoteRef:
        key: SQL_ENGINE
    - secretKey: REDIS_URL
      remoteRef:
        key: REDIS_URL